name: panvimdoc

on:
  push:
    branches:
      - test/workflow

jobs:
  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    steps:
      - uses: actions/checkout@v2
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: sidebar
          description: ""
          pandoc: "doc/general.md"
          toc: true
          version: "NVIM v0.6.0"
      - uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update report
          token: ${{ secrets.PAT }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: "docs/auto-update"
          delete-branch: true
          base: "main"
          title: '[docs]: Update documentation'
