name: Generate Documentation

on:
  push:
    branches:
      - test/workflow
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    steps:
      - uses: actions/checkout@v2
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: sidebar
          # Show Last Change on header
          description: ""
          # Input file
          pandoc: "doc/general.md"
          # Show Table of Content
          toc: true
          version: "NVIM v0.6.0"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs(gen): update"
          branch: ${{ github.head_ref }}
