name: Generate Documentation

on:
  push:
    branches:
      - test/workflow

jobs:
  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    steps:
      - uses: actions/checkout@v2
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: sidebar
          # Show Last Change on header
          description: ""
          # Input file
          pandoc: "doc/general.md"
          # Show Table of Content
          toc: true
          version: "NVIM v0.6.0"
      - uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "docs(gen): update"
          author: Github Action <action@users.noreply.github.com>
          branch: "docs/auto-update"
          delete-branch: true
          base: "main"
          title: "docs(gen): update"
          body: |
            Update documentation
